### ISSUE TITLE
在luajit 2.0 下报错了

### ISSUE THREAD

**Issue by xinqiyang** [cloudwu/lua-int64#3]
hi.....

最近我想在openresty下集成这个Int64的模块,这里用的是luajit2.0.2,现在编译的时候,实用jit的库编译会出warning...而且跑起来出现以下错误

/usr/local/lualib/int64.so: undefined symbol: luaL_buffinitsize

看了文章后http://blog.codingnow.com/2012/09/lua_52_changes.html 后,发现是luajit和lua5.2之间的兼容性问题

这块能修正后在luajit下实现的么? 
谢谢!

**Comment by cloudwu** [comment]
luajit 即使在 64bit 平台下， 也利用了 NaN Trick, 它的 lightuserdata 不是 64 位的， 所以这个库不可能在 luajit 下使用。

**Comment by xinqiyang** [comment]
恩...谢谢云风老大的回复,我在想替代方案,现在用twitter的snowflake来提供了...之前想的如果luajit下能实现的话int64自增的话就好了......
